apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-chart
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/sidhuni/webapp-annotations.git'
    targetRevision: main        # or master or branch name
    path: .    # folder where Chart.yaml exists
    helm:
      releaseName: web-app1 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true